### ISSUE TITLE
Tabs are difficult to read in dark mode

### ISSUE THREAD

**Issue by stuartlangridge** [UbuntuAccomplishments/viewer#1]
![image](https://user-images.githubusercontent.com/4356350/143297735-bdcfaf6e-8766-4b25-b2c2-5ff9cc0175d5.png)

See "Opportunities" in the screenshot, which is purple on grey and almost impossible to read.

**Comment by lucyllewy** [comment]
This is down to the yaru.dart theme. I guess this should be forwarded to https://github.com/ubuntu/yaru.dart?

**Comment by stuartlangridge** [comment]
I think it might be https://github.com/ubuntu/yaru.dart/issues/54 which is marked as fixed?

**Comment by lucyllewy** [comment]
Aah, I am wrong, the viewer does explicitly specify. A fix for it is coming shortly.
