### ISSUE TITLE
Some trophies show in both My Trophies and Opportunities

### ISSUE THREAD

**Issue by stuartlangridge** [UbuntuAccomplishments/viewer#3]
My Trophies containing "Populist on Ask Ubuntu":

![image](https://user-images.githubusercontent.com/4356350/143314658-312a2fd5-a207-48f2-a58c-5674e8647c1d.png)

Opportunities containing "Populist on Ask Ubuntu":

![image](https://user-images.githubusercontent.com/4356350/143314617-c86ac507-b1d8-4c2b-a22f-5c15ecb09c0f.png)

**Comment by lucyllewy** [comment]
The way I have been treating the opportunities tab is a list of all trophies, whether you've achieved them or not, and then just the ones you've achieved in the "My Trophies" list. I can be persuaded to hide all the achieved trophies in the opportunities list. Would that still warrant the opportunities, which would all be unachieved, to be greyed out (opacity applied to them) indicating the non achievement the way it is now?

Edit to add: or maybe grey out the ones that are locked and make the achievable ones that are unlocked full brightness to indicate their accessibility?

**Comment by stuartlangridge** [comment]
Two thoughts there:

1. if the list contains all trophies then it's not a list of "opportunities", in the same way that you would be sad if I contacted you with an exciting job opportunity which turned out to be the job you're already doing
2. while I appreciate that some of the trophies are made semi-transparent, it doesn't _look_ like that. Because of the symbolic style of the trophy imagery on its static colour background, combined with how there are trophies in multiple colours already (gold, silver, bronze, blue), a "greyed out" trophy doesn't look _disabled_, it just looks "dark orange". See "Precognitive" in the screenshot above; sure, I can kinda see that it's disabled, but it doesn't stand out that way at all. More importantly, since this is a list of opportunities, greying out the ones that actually _are_ opportunities de-emphasises them which is the opposite of what you want.

So my inclination is to make "opportunities" mean "trophies you haven't got"; that way they _are_ opportunities, plus you don't have to worry about greying some out unclearly.
